uri=jdbc:oracle:thin:GESFIN/sof@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=gpexax8mnod-hrpot-scan.sbnbdpro.vcndb.oraclevcn.com)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=GFIN)(FAILOVER_MODE=(TYPE=select)(METHOD=basic))))
# Timeout de checkout de conexion ampliado a 30 s.
checkoutTimeout=30000
idleConnectionTestPeriod=60
testConnectionOnCheckout=S