
# 1. Datos reales de Supabase
spring.datasource.url=jdbc:postgresql://db.ID_DE_PROYECTO.supabase.co:5432/postgres
spring.datasource.username=postgres.fosephxtagbzyvbluhbv
spring.datasource.password=DIVIDINGworlds2026
spring.datasource.driver-class-name=org.postgresql.Driver

## 2. Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect