# CONFIGURACIÓN PARA BASE DE DATOS LOCAL (H2)
spring.datasource.url=jdbc:h2:mem:wealthhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto hace que las tablas se creen en la memoria RAM automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Esto activa una consola web para ver tus tablas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console